### ISSUE TITLE
Getting RClone encryption to work

### ISSUE THREAD

**Issue by Deiteq** [Admin9705/The-Awesome-Plex-Server#16]
@Admin9705 
Hey, I found it best to install and run plexdrive first then install and config rclone after.
I used plexdrive5 as I was having problems with plexdrive4 for some reason.
Configured rclone as usual and added a new rclonecrypt drive that links to `/mnt/plexdrive5/crypt` (crypt being my encrypted folder within gdrive).
Used your original plexdrive5 instructions [http://doc.plexguide.com/](url) part 5 and added `allow_non_empty_mount,` then input relevant details and pressed Ctrl+A then D to detach from screen, this then gives the screen name/number to reattach later with `screen -r` (i.e. `screen -r 3458`), plus if you ssh in again you can type `screen -list` to give you the screen name/number as long as the server wasn't rebooted.

I suppose people could still use the `zilch` folder for rclonecrypt, depends if they want to use their old encrypted folder or not.

Anyway, I'm editing the RClone and the Plexdrive instructions a little so you can go through and check if it's worth keeping or not, but I'm basically copy and pasting your previous instructions as this is how I've got it to work.

**Comment by Deiteq** [comment]
@Admin9705 
Hey, not sure if I’m suppose to click on the Pull Request button after I edit the instructions or not, haven't really used GitHub before this project, opened an account as it was a requirement for one of the coding classes I was checking out.
Apologies in advance if I'm not meant to!

**Comment by Admin9705** [comment]
No, your fine.  It doesn't mess up anything.  So click branch on the front and then select version 3.  I'm rewriting the thing and getting rid of docker.  Docker is great, but complicates upgrades, paths, and permissions.  I used docker because I couldn't figure how to make the services start up properly, but now I do with tons of other crap gained from the two month prior switch.  I already have sonnar and sab running in services; something I couldn't do.  As a result, there will be no more blackhole issues, security should be easier, and etc.  I appreciate that your helping with the amount of on the go I have do here.  How is the plex for you?  Hopefully, you gained something out of this two.  When I finish version 3, I'll switch it to being the master and keep the other one as legacy, incase someone wants to play with docker or docker one item.  I'll even put up the instructions to install apapche and everything.  Docker doesnt get allowing well with the web instructions stuff.

**Comment by Deiteq** [comment]
Hmm, just realised that we will need to point plex to /mnt/rclone so that plex can see the decrypted content, not sure what other apps will need to be directed that way too.

Just noticed your reply, shame about docker, was hoping that was the future....as it's similar to quickbox easy to install but could work better on lower powered systems!

I have gained a lot from this, haven't actually continued with the plex part as I was trying to get the encryption part figured out, although last night I did start to watch 21 Grams but was too tired to finish it, maybe tonight though....super impressed with the library size!

I look forward to trying out version 3 then, thanks for putting all this together!

**Comment by Admin9705** [comment]
ya docker is good, but complicates everything.  a good thing about the services working now is that I can restart a program by using sudo systemctl restart xxx.service ~ makes it easy it reboot now; a prior problem I had.  If I had to reboot something, the whole system had 2.
