### ISSUE TITLE
/media/movies and /media/tvdont exist 

### ISSUE THREAD

**Issue by daveftw84** [Admin9705/The-Awesome-Plex-Server#22]
im using /mnt/plexdrive4/zilch/movies and /mnt/plexdrive4/zilch/tv  for now. is this correct or am i missing something?
 i tried typing it in but it comes up empty after scanning

**Comment by Admin9705** [comment]
this is correct. i don't have anything that's /media/tv or /media/movies... carefully go over the instructions. one typo can cause it to not start

**Comment by daveftw84** [comment]
its in instructions still

**Comment by daveftw84** [comment]
thanks for everything you do

**Comment by Admin9705** [comment]
Oh your fine, we are learning together. I’ll jump on it this week

**Comment by Admin9705** [comment]
@daveftw84 , fixed the insturctions.  I had no issues because I knew what to type and didn't follow my own instructions; those were based of old ones.  Made the update...

### Configuring TV Shows 
# [Click] Add Library
# [Click] TV Shows
# [Type] Add Folders to Your Library: /mnt/plexdrive4/zilch/tv     <<< You will never be able to select it; type it and hit ok
# [Click] Ok

### Configuring Movies 
# [Click] Add Library
# [Click] Films
# [Type] Add Folders to Your Library: /mnt/plexdrive4/zilch/movies     <<< You will never be able to select it; type it and hit ok
# [Click] Ok

-------------
Thanks, let me know if it works.
